# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create!(user_name:"8mada", email: "test1@test.co.jp", password: "zxcvbnm",  introduction: "ライブの空間が大好きです。")
User.create!(user_name:"tarou2933", email: "test2@test.co.jp", password: "zxcvbnm",  introduction: "年30回ライブを求めて日本を駆け巡っています。")
User.create!(user_name:"fukaevenote", email: "test3@test.co.jp", password: "zxcvbnm",  introduction: "ジャズピアノをしています。バーで演奏させてもらってます。")
User.create!(user_name:"watakaori407", email: "test4@test.co.jp", password: "zxcvbnm",  introduction: "舞台鑑賞が趣味です。")
User.create!(user_name:"i_am_rino", email: "test5@test.co.jp", password: "zxcvbnm",  introduction: "博物館・美術館に行くのが趣味です。共通の趣味の方、お話ししましょう。")
User.create!(user_name:"xx_makiho26_xx", email: "test6@test.co.jp", password: "zxcvbnm",  introduction: "K-POPが好きな20代です。")
User.create!(user_name:"satoudesu", email: "test7@test.co.jp", password: "zxcvbnm",  introduction: "オーケストラコンサートによく行きます。")
User.create!(user_name:"jiny_way_box", email: "test8@test.co.jp", password: "zxcvbnm",  introduction: "趣味は美術館巡りです。好きな画家はモネです。")
User.create!(user_name:"everything_like", email: "test9@test.co.jp", password: "zxcvbnm",  introduction: "よくお笑いライブに通っています。面白い芸人さんたくさん知ってます。")
User.create!(user_name:"luckey_dayo", email: "test10@test.co.jp", password: "zxcvbnm",  introduction: "お笑い芸人の笑い麺が大好きです。")

Relationship.create!(follower_id:1,followed_id:2)
Relationship.create!(follower_id:1,followed_id:3)
Relationship.create!(follower_id:1,followed_id:4)
Relationship.create!(follower_id:2,followed_id:1)
Relationship.create!(follower_id:2,followed_id:5)
Relationship.create!(follower_id:3,followed_id:8)
Relationship.create!(follower_id:4,followed_id:1)
Relationship.create!(follower_id:4,followed_id:2)
Relationship.create!(follower_id:4,followed_id:6)
Relationship.create!(follower_id:7,followed_id:5)
Relationship.create!(follower_id:8,followed_id:3)
Relationship.create!(follower_id:9,followed_id:10)
Relationship.create!(follower_id:10,followed_id:9)

Ticket.create!(user_id: 1, event_name: "stormライブビューイング", event_date: "2022-01-10", number: 2, money: 6000, entry_start_date: "2021-10-01", entry_end_date: "2021-10-10", entry_flg: true, win_date: "2021-10-20", win_flg: true, payment_date: "2021-10-27", payment_flg: true)
Ticket.create!(user_id: 1, event_name: "TVステ（番組協力）", event_date: "2022-02-15", number: nil, money: nil, entry_start_date: "2022-01-15", entry_end_date: "2022-01-17", entry_flg: true, win_date: "2022-01-21", win_flg: false, payment_date: nil, payment_flg: false)
Ticket.create!(user_id: 1, event_name: "DMMライブ", event_date: "2022-03-01", number: 2, money: 5000, entry_start_date: "2022-01-03", entry_end_date: "2022-01-14", entry_flg: true, win_date: "2022-01-22", win_flg: true, payment_date: "2022-03-05", payment_flg: false)
Ticket.create!(user_id: 1, event_name: "中原みきひとり語り", event_date: "2022-03-10", number: 2, money: 8000, entry_start_date: "2021-12-10", entry_end_date: "2021-12-25", entry_flg: true, win_date: "2022-01-10", win_flg: true, payment_date: "2022-01-17", payment_flg: true)
Ticket.create!(user_id: 1, event_name: "storm全国ツアー公演", event_date: "2022-05-15", number: 2, money: 9500, entry_start_date: "2022-03-15", entry_end_date: "2022-03-31", entry_flg: false, win_date: "2022-04-10", win_flg: nil, payment_date: nil, payment_flg: false)
Ticket.create!(user_id: 1, event_name: "storm全国ツアー公演", event_date: "2022-06-24", number: 2, money: 9500, entry_start_date: "2022-03-15", entry_end_date: "2022-03-31", entry_flg: false, win_date: "2022-04-10", win_flg: nil, payment_date: nil, payment_flg: false)
Ticket.create!(user_id: 1, event_name: "大山夏フェス", event_date: "2022-08-10", number: 4, money: 6500, entry_start_date: "2022-05-01", entry_end_date: "2022-05-10", entry_flg: false, win_date: "2022-05-20", win_flg: nil, payment_date: nil, payment_flg: false)

Event.create!(user_id: 1, name: "stormライブビューイング", date: "2022-01-10", open_time: "2000-01-01 11:00:00", start_time: "2000-01-01 12:00:00", end_time: "2000-01-01 14:00:00", artist: "storm", place: "神戸文化会館", seat: "H列ー３５,H列ー３６", with: "みきちゃん", memo: "")
Event.create!(user_id: 1, name: "友達の路上ライブ", date: "2022-02-04", open_time: nil, start_time: "2000-01-01 19:00:00", end_time: nil, artist: "", place: "大阪", seat: "", with: "", memo: "仕事終わりに行く", release_flg: false)
Event.create!(user_id: 1, name: "DMMライブ", date: "2022-03-01", open_time: "2000-01-01 12:00:00", start_time: "2000-01-01 14:00:00", end_time: "2000-01-01 15:30:00", artist: "DMM", place: "都マッサ", seat: "", memo: "", release_flg: true, with: "")
Event.create!(user_id: 1, name: "中原みきひとり語り", date: "2022-03-10", open_time: "2000-01-01 16:30:00", start_time: "2000-01-01 18:00:00", end_time: "2000-01-01 20:00:00", artist: "中原みき", place: "大津市民ホール", seat: "G列ー１２.G列ー１３", with: "母", memo: "現地集合", release_flg: true)
Event.create!(user_id: 1, name: "storm全国ツアー公演", date: "2022-05-15", open_time: "2000-01-01 16:00:00", start_time: "2000-01-01 18:00:00", end_time: "2000-01-01 21:00:00", artist: "storm", place: "京都ドーム", seat: "", with: "", memo: "", release_flg: false)
Event.create!(user_id: 1, name: "storm全国ツアー公演", date: "2022-06-24", open_time: "2000-01-01 16:00:00", start_time: "2000-01-01 18:00:00", end_time: "2000-01-01 21:00:00", artist: "storm", place: "福川ドーム", seat: "", with: "", memo: "", release_flg: false)
Event.create!(user_id: 1, name: "大山夏フェス", date: "2022-08-10", open_time: "2000-01-01 00:00:00", start_time: "2000-01-01 12:00:00", end_time: "2000-01-01 20:00:00", artist: "バンド", place: "大山野外特設ステージ", seat: "", with: "たけし、りょう、さやか", memo: "大学のメンバーと", release_flg: true)

Post.create!(user_id:1, post_image: File.open("./app/assets/images/user1-1.jpeg"), maintext:"ライブ参戦")
Post.create!(user_id:1, post_image: File.open("./app/assets/images/user1-2.jpeg"), maintext:"中学の友達と行ったライブ")
Post.create!(user_id:1, post_image: File.open("./app/assets/images/user1-3.jpeg"), maintext:"初めて行ったジャズコンサート。ジャズ最高です。")
Post.create!(user_id:1, post_image: File.open("./app/assets/images/user1-4.jpeg"), maintext:"最近デジタル調の曲にハマってます。おすすめ教えてください！")
Post.create!(user_id:1, post_image: File.open("./app/assets/images/user1-5.jpeg"), maintext:"なつかしのライブ。もう一度行きたいな・・・")
Post.create!(user_id:1, post_image: File.open("./app/assets/images/user1-6.jpeg"), maintext:"アイドルのライブに参戦。会場のサイリウムがとても綺麗だった。")
Post.create!(user_id:2, post_image: File.open("./app/assets/images/user2-1.jpeg"), maintext:"moonのライブで北海道まで。秋だけど寒かった。")
Post.create!(user_id:2, post_image: File.open("./app/assets/images/user2-2.jpeg"), maintext:"福岡の路上ライブに参戦した時の一枚。もう一度行きたいな。")
Post.create!(user_id:2, post_image: File.open("./app/assets/images/user2-3.jpeg"), maintext:"屋外ライブ。花火が最高に綺麗だった。")
Post.create!(user_id:3, post_image: File.open("./app/assets/images/user3-1.jpeg"), maintext:"2022/5/5大阪でジャズライブを開催します。よければ来てください。")
Post.create!(user_id:3, post_image: File.open("./app/assets/images/user3-2.jpeg"), maintext:"一人で弾くのもいいけど、やっぱりセッションはいいね。")
Post.create!(user_id:3, post_image: File.open("./app/assets/images/user3-3.jpeg"), maintext:"ライブ終わりにbarで一杯。ここで弾かせてもらってから早5年。")
Post.create!(user_id:4, post_image: File.open("./app/assets/images/user4-1.jpeg"), maintext:"舞台「マクべクス」。笑いあり涙ありの最高の舞台。")
Post.create!(user_id:4, post_image: File.open("./app/assets/images/user4-2.jpeg"), maintext:"歌もダンスも最高の霰組！")
Post.create!(user_id:4, post_image: File.open("./app/assets/images/user4-3.jpeg"), maintext:"初めて歌舞伎を見に行った。迫力があってとても楽しめた！")
Post.create!(user_id:5, post_image: File.open("./app/assets/images/user5-1.jpeg"), maintext:"昔行った海外の美術館。全部見るのに２日かかりました。写真①")
Post.create!(user_id:5, post_image: File.open("./app/assets/images/user5-2.jpeg"), maintext:"昔行った海外の美術館。全部見るのに２日かかりました。写真②")
Post.create!(user_id:5, post_image: File.open("./app/assets/images/user5-3.jpeg"), maintext:"近現代アートや建築デザインドローイング、写真があって見ごたえ抜群。")
Post.create!(user_id:6, post_image: File.open("./app/assets/images/user6-1.jpeg"), maintext:"WHITE BULUE最高！")
Post.create!(user_id:9, post_image: File.open("./app/assets/images/user9-1.jpeg"), maintext:"2022/3/3 吉原劇場で若手お笑い芸人のライブがあります！面白い芸人たくさん出るので是非！")
Post.create!(user_id:9, post_image: File.open("./app/assets/images/user9-2.jpeg"), maintext:"漫才の面白さを広めたい。")