# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create!(user_name:"8mada", email: "test1@test.co.jp", password: "zxcvbnm", profile_image: File.open("./app/assets/images/user1.jpeg"),  introduction: "ライブの空間が大好きです。")
User.create!(user_name:"tarou2933", email: "test2@test.co.jp", password: "zxcvbnm", profile_image: File.open("./app/assets/images/user2.jpeg"),  introduction: "年30回ライブを求めて日本を駆け巡っています。")
User.create!(user_name:"fukaevenote", email: "test3@test.co.jp", password: "zxcvbnm", profile_image: File.open("./app/assets/images/user3.jpeg"),  introduction: "ジャズピアノをしています。バーで演奏させてもらってます。")
User.create!(user_name:"watakaori407", email: "test4@test.co.jp", password: "zxcvbnm",  introduction: "舞台鑑賞が趣味です。")
User.create!(user_name:"i_am_rino", email: "test5@test.co.jp", password: "zxcvbnm", profile_image: File.open("./app/assets/images/user5.jpeg"),  introduction: "博物館・美術館に行くのが趣味です。共通の趣味の方、お話ししましょう。")
User.create!(user_name:"xx_makiho26_xx", email: "test6@test.co.jp", password: "zxcvbnm", profile_image: File.open("./app/assets/images/user6.jpeg"),  introduction: "K-POPが好きな20代です。")
User.create!(user_name:"satoudesu", email: "test7@test.co.jp", password: "zxcvbnm", profile_image: File.open("./app/assets/images/user7.jpeg"),  introduction: "オーケストラコンサートによく行きます。")
User.create!(user_name:"jiny_way_box", email: "test8@test.co.jp", password: "zxcvbnm", profile_image: File.open("./app/assets/images/user8.jpeg"),  introduction: "趣味は美術館巡りです。好きな画家はモネです。")
User.create!(user_name:"everything_like", email: "test9@test.co.jp", password: "zxcvbnm", profile_image: File.open("./app/assets/images/user9.jpeg"),  introduction: "よくお笑いライブに通っています。面白い芸人さんたくさん知ってます。")
User.create!(user_name:"luckey_dayo", email: "test10@test.co.jp", password: "zxcvbnm", profile_image: File.open("./app/assets/images/user10.jpeg"),  introduction: "お笑い芸人の笑い麺が大好きです。")

Relationship.create!(follower_id:1,followed_id:2)
Relationship.create!(follower_id:1,followed_id:3)
Relationship.create!(follower_id:1,followed_id:4)
Relationship.create!(follower_id:2,followed_id:1)
Relationship.create!(follower_id:2,followed_id:5)
Relationship.create!(follower_id:3,followed_id:8)
Relationship.create!(follower_id:4,followed_id:1)
Relationship.create!(follower_id:4,followed_id:2)
Relationship.create!(follower_id:4,followed_id:6)
Relationship.create!(follower_id:7,followed_id:5)
Relationship.create!(follower_id:8,followed_id:3)
Relationship.create!(follower_id:9,followed_id:10)
Relationship.create!(follower_id:10,followed_id:9)

Ticket.create!(user_id: 1, event_name: "stormライブビューイング", event_date: "2022-01-10", number: 2, money: 6000, entry_start_date: "2021-10-01", entry_end_date: "2021-10-10", entry_flg: true, win_date: "2021-10-20", win_flg: true, payment_date: "2021-10-27", payment_flg: true)
Ticket.create!(user_id: 1, event_name: "TVステ（番組協力）", event_date: "2022-02-15", number: nil, money: nil, entry_start_date: "2022-01-15", entry_end_date: "2022-01-17", entry_flg: true, win_date: "2022-01-21", win_flg: false, payment_date: nil, payment_flg: false)
Ticket.create!(user_id: 1, event_name: "DMMライブ", event_date: "2022-03-01", number: 2, money: 5000, entry_start_date: "2022-01-03", entry_end_date: "2022-01-14", entry_flg: true, win_date: "2022-01-22", win_flg: true, payment_date: "2022-03-05", payment_flg: false)
Ticket.create!(user_id: 1, event_name: "中原みきひとり語り", event_date: "2022-03-10", number: 2, money: 8000, entry_start_date: "2021-12-10", entry_end_date: "2021-12-25", entry_flg: true, win_date: "2022-01-10", win_flg: true, payment_date: "2022-01-17", payment_flg: true)
Ticket.create!(user_id: 1, event_name: "storm全国ツアー公演", event_date: "2022-05-15", number: 2, money: 9500, entry_start_date: "2022-03-15", entry_end_date: "2022-03-31", entry_flg: false, win_date: "2022-04-10", win_flg: nil, payment_date: nil, payment_flg: false)
Ticket.create!(user_id: 1, event_name: "storm全国ツアー公演", event_date: "2022-06-24", number: 2, money: 9500, entry_start_date: "2022-03-15", entry_end_date: "2022-03-31", entry_flg: false, win_date: "2022-04-10", win_flg: nil, payment_date: nil, payment_flg: false)
Ticket.create!(user_id: 1, event_name: "大山夏フェス", event_date: "2022-08-10", number: 4, money: 6500, entry_start_date: "2022-05-01", entry_end_date: "2022-05-10", entry_flg: false, win_date: "2022-05-20", win_flg: nil, payment_date: nil, payment_flg: false)
Ticket.create!(user_id: 3, event_name: "クリスマスコンサート", event_date: "2021-12-25", number: 2, money: 8000, entry_start_date: "2021-11-15", entry_end_date: "2021-11-25", entry_flg: true, win_date: "2021-11-30", win_flg: true, payment_date: "2021-12-07", payment_flg: true)
Ticket.create!(user_id: 3, event_name: "高島かおりピアノコンサート", event_date: "2022-03-01", number: 2, money: 7500, entry_start_date: "2022-01-15", entry_end_date: "2022-01-20", entry_flg: true, win_date: "2022-01-25", win_flg: false, payment_date: nil, payment_flg: false)
Ticket.create!(user_id: 3, event_name: "bar「マッシュ」で弾き語りコンサート", event_date: "2022-05-05", number: nil, money: nil, entry_start_date: "2022-03-20", entry_end_date: "2022-03-30", entry_flg: false, win_date: nil, win_flg: nil, payment_date: nil, payment_flg: false)
Ticket.create!(user_id: 4, event_name: "2月大歌舞伎", event_date: "2022-02-20", number: 1, money: 12000, entry_start_date: "2022-01-10", entry_end_date: nil, entry_flg: true, win_date: nil, win_flg: nil, payment_date: nil, payment_flg: true)
Ticket.create!(user_id: 4, event_name: "舞台マクベス", event_date: "2022-04-08", number: 1, money: 8000, entry_start_date: "2022-02-20", entry_end_date: "2022-01-28", entry_flg: false, win_date: nil, win_flg: nil, payment_date: nil, payment_flg: false)
Ticket.create!(user_id: 4, event_name: "霰組公演かぜと", event_date: "2022-05-05", number: 1, money: 7500, entry_start_date: "2022-04-01", entry_end_date: "2022-04-10", entry_flg: false, win_date: nil, win_flg: nil, payment_date: nil, payment_flg: false)

Event.create!(user_id: 1, name: "stormライブビューイング", date: "2022-01-10", open_time: "2000-01-01 11:00:00", start_time: "2000-01-01 12:00:00", end_time: "2000-01-01 14:00:00", artist: "storm", place: "神戸文化会館", seat: "H列ー３５,H列ー３６", with: "みきちゃん", memo: "")
Event.create!(user_id: 1, name: "友達の路上ライブ", date: "2022-02-04", open_time: nil, start_time: "2000-01-01 19:00:00", end_time: nil, artist: "", place: "大阪", seat: "", with: "", memo: "仕事終わりに行く", release_flg: false)
Event.create!(user_id: 1, name: "DMMライブ", date: "2022-03-01", open_time: "2000-01-01 12:00:00", start_time: "2000-01-01 14:00:00", end_time: "2000-01-01 15:30:00", artist: "DMM", place: "都マッサ", seat: "", memo: "", release_flg: true, with: "")
Event.create!(user_id: 1, name: "中原みきひとり語り", date: "2022-03-10", open_time: "2000-01-01 16:30:00", start_time: "2000-01-01 18:00:00", end_time: "2000-01-01 20:00:00", artist: "中原みき", place: "大津市民ホール", seat: "G列ー１２.G列ー１３", with: "母", memo: "現地集合", release_flg: true)
Event.create!(user_id: 1, name: "storm全国ツアー公演", date: "2022-05-15", open_time: "2000-01-01 16:00:00", start_time: "2000-01-01 18:00:00", end_time: "2000-01-01 21:00:00", artist: "storm", place: "京都ドーム", seat: "", with: "", memo: "", release_flg: false)
Event.create!(user_id: 1, name: "storm全国ツアー公演", date: "2022-06-24", open_time: "2000-01-01 16:00:00", start_time: "2000-01-01 18:00:00", end_time: "2000-01-01 21:00:00", artist: "storm", place: "福川ドーム", seat: "", with: "", memo: "", release_flg: false)
Event.create!(user_id: 1, name: "大山夏フェス", date: "2022-08-10", open_time: "2000-01-01 00:00:00", start_time: "2000-01-01 12:00:00", end_time: "2000-01-01 20:00:00", artist: "バンド", place: "大山野外特設ステージ", seat: "", with: "たけし、りょう、さやか", memo: "大学のメンバーと", release_flg: true)
Event.create!(user_id: 3, name: "クリスマスコンサート", date: "2021-12-25", open_time: "2000-01-01 17:00:00", start_time: "2000-01-01 18:00:00", end_time: "2000-01-01 20:00:00", artist: "みなとシンフォニー", place: "みなとコンサートホール", seat: "K列ー２７,K列－２８", with: "母", memo: "", release_flg: true, boolean: false)
Event.create!(user_id: 3, name: "bar「マッシュ」で弾き語りコンサート", date: "2022-05-05", open_time: "2000-01-01 11:00:00", start_time: "2000-01-01 12:00:00", end_time: "2000-01-01 14:00:00", artist: "", place: "", seat: "", with: "", memo: "", release_flg: true, boolean: false)
Event.create!(user_id: 4, name: "2月大歌舞伎", date: "2022-02-20", open_time: "2000-01-01 11:00:00", start_time: "2000-01-01 12:00:00", end_time: "2000-01-01 15:00:00", artist: "中村市之亟他", place: "京都歌舞練場", seat: "C列ー５", with: "", memo: "", release_flg: true, boolean: false)
Event.create!(user_id: 4, name: "舞台マクベス", date: "2022-04-08", open_time: "2000-01-01 13:00:00", start_time: "2000-01-01 14:00:00", end_time: "2000-01-01 16:30:00", artist: "西岡秀敏他", place: "OSホール", seat: "", with: "", memo: "", release_flg: true, boolean: false)
Event.create!(user_id: 4, name: "霰組公演かぜと", date: "2022-05-05", open_time: "2000-01-01 11:00:00", start_time: "2000-01-01 12:00:00", end_time: "2000-01-01 14:30:00", artist: "", place: "夢歌劇大ホール", seat: "", with: "", memo: "", release_flg: false, boolean: false)

Item.create!(event_id: 1, name: "パンフレット", quantity: 2, price: 1200, buy_flg: false)
Item.create!(event_id: 1, name: "ペンライト", quantity: 1, price: 1500, buy_flg: false)
Item.create!(event_id: 1, name: "うちわ", quantity: 1, price: 800, buy_flg: false)
Item.create!(event_id: 3, name: "Tシャツ", quantity: 1, price: 3600, buy_flg: false)
Item.create!(event_id: 3, name: "タオル", quantity: 2, price: 1800, buy_flg: false)

Album.create!(user_id:1, event_id:1, album_name:"stormライブビューイング")
Album.create!(user_id:1, event_id:1, album_name:"Menory")
Album.create!(user_id:1, event_id:2, album_name:"路上ライブ")
Album.create!(user_id:3, event_id:8, album_name:"クリスマスコンサート")

Photo.create!(album_id:1, memory_image: File.open("./app/assets/images/album1-1.jpeg"))
Photo.create!(album_id:1, memory_image: File.open("./app/assets/images/album1-2.jpeg"))
Photo.create!(album_id:1, memory_image: File.open("./app/assets/images/album1-3.jpeg"))
Photo.create!(album_id:2, memory_image: File.open("./app/assets/images/album2-1.jpeg"))
Photo.create!(album_id:2, memory_image: File.open("./app/assets/images/album2-2.jpeg"))
Photo.create!(album_id:3, memory_image: File.open("./app/assets/images/album3-1.jpeg"))
Photo.create!(album_id:3, memory_image: File.open("./app/assets/images/album3-2.jpeg"))
Photo.create!(album_id:3, memory_image: File.open("./app/assets/images/album3-3.jpeg"))
Photo.create!(album_id:4, memory_image: File.open("./app/assets/images/album4-1.jpeg"))
Photo.create!(album_id:4, memory_image: File.open("./app/assets/images/album4-2.jpeg"))
Photo.create!(album_id:4, memory_image: File.open("./app/assets/images/album4-3.jpeg"))
Photo.create!(album_id:4, memory_image: File.open("./app/assets/images/album4-4.jpeg"))
Photo.create!(album_id:4, memory_image: File.open("./app/assets/images/album4-5.jpeg"))

Post.create!(user_id:1, post_image: File.open("./app/assets/images/user1-1.jpeg"), maintext:"ライブ参戦")
Post.create!(user_id:1, post_image: File.open("./app/assets/images/user1-2.jpeg"), maintext:"中学の友達と行ったライブ")
Post.create!(user_id:1, post_image: File.open("./app/assets/images/user1-3.jpeg"), maintext:"初めて行ったジャズコンサート。ジャズ最高です。")
Post.create!(user_id:1, post_image: File.open("./app/assets/images/user1-4.jpeg"), maintext:"最近デジタル調の曲にハマってます。おすすめ教えてください！")
Post.create!(user_id:1, post_image: File.open("./app/assets/images/user1-5.jpeg"), maintext:"なつかしのライブ。もう一度行きたいな・・・")
Post.create!(user_id:1, post_image: File.open("./app/assets/images/user1-6.jpeg"), maintext:"アイドルのライブに参戦。会場のサイリウムがとても綺麗だった。")
Post.create!(user_id:2, post_image: File.open("./app/assets/images/user2-1.jpeg"), maintext:"moonのライブで北海道まで。秋だけど寒かった。")
Post.create!(user_id:2, post_image: File.open("./app/assets/images/user2-2.jpeg"), maintext:"福岡の路上ライブに参戦した時の一枚。もう一度行きたいな。")
Post.create!(user_id:2, post_image: File.open("./app/assets/images/user2-3.jpeg"), maintext:"屋外ライブ。花火が最高に綺麗だった。")
Post.create!(user_id:3, post_image: File.open("./app/assets/images/user3-1.jpeg"), maintext:"2022/5/5大阪でジャズライブを開催します。よければ来てください。")
Post.create!(user_id:3, post_image: File.open("./app/assets/images/user3-2.jpeg"), maintext:"一人で弾くのもいいけど、やっぱりセッションはいいね。")
Post.create!(user_id:3, post_image: File.open("./app/assets/images/user3-3.jpeg"), maintext:"ライブ終わりにbarで一杯。ここで弾かせてもらってから早5年。")
Post.create!(user_id:4, post_image: File.open("./app/assets/images/user4-1.jpeg"), maintext:"舞台「マクべクス」。笑いあり涙ありの最高の舞台。")
Post.create!(user_id:4, post_image: File.open("./app/assets/images/user4-2.jpeg"), maintext:"歌もダンスも最高の霰組！")
Post.create!(user_id:4, post_image: File.open("./app/assets/images/user4-3.jpeg"), maintext:"初めて歌舞伎を見に行った。迫力があってとても楽しめた！")
Post.create!(user_id:5, post_image: File.open("./app/assets/images/user5-1.jpeg"), maintext:"昔行った海外の美術館。全部見るのに２日かかりました。写真①")
Post.create!(user_id:5, post_image: File.open("./app/assets/images/user5-2.jpeg"), maintext:"昔行った海外の美術館。全部見るのに２日かかりました。写真②")
Post.create!(user_id:5, post_image: File.open("./app/assets/images/user5-3.jpeg"), maintext:"近現代アートや建築デザインドローイング、写真があって見ごたえ抜群。")
Post.create!(user_id:6, post_image: File.open("./app/assets/images/user6-1.jpeg"), maintext:"WHITE BULUE最高！")
Post.create!(user_id:9, post_image: File.open("./app/assets/images/user9-1.jpeg"), maintext:"2022/3/3 吉原劇場で若手お笑い芸人のライブがあります！面白い芸人たくさん出るので是非！")
Post.create!(user_id:9, post_image: File.open("./app/assets/images/user9-2.jpeg"), maintext:"漫才の面白さを広めたい。")

Tag.create!(tag_name: "ライブ")
Tag.create!(tag_name: "アイドル")
Tag.create!(tag_name: "サイリウム")
Tag.create!(tag_name: "屋外ライブ")
Tag.create!(tag_name: "夏")
Tag.create!(tag_name: "ビール片手に")
Tag.create!(tag_name: "Pelum")
Tag.create!(tag_name: "デジタル調")
Tag.create!(tag_name: "ジャズ")
Tag.create!(tag_name: "ピアノ")
Tag.create!(tag_name: "bar")
Tag.create!(tag_name: "遠征ライブ")
Tag.create!(tag_name: "快晴")
Tag.create!(tag_name: "Eve2022")
Tag.create!(tag_name: "アリーナ")
Tag.create!(tag_name: "ファンサ")
Tag.create!(tag_name: "banndo")
Tag.create!(tag_name: "花火")
Tag.create!(tag_name: "5000")
Tag.create!(tag_name: "5000人")
Tag.create!(tag_name: "福岡")
Tag.create!(tag_name: "駅前")
Tag.create!(tag_name: "路上ライブ")
Tag.create!(tag_name: "博多ラーメン")
Tag.create!(tag_name: "北海道")
Tag.create!(tag_name: "雪")
Tag.create!(tag_name: "5年")
Tag.create!(tag_name: "お酒")
Tag.create!(tag_name: "jaz")
Tag.create!(tag_name: "セッション")
Tag.create!(tag_name: "jazz")
Tag.create!(tag_name: "大阪")
Tag.create!(tag_name: "ジャズライブ")
Tag.create!(tag_name: "歌舞伎")
Tag.create!(tag_name: "中村座")
Tag.create!(tag_name: "霰組")
Tag.create!(tag_name: "女役")
Tag.create!(tag_name: "男役")
Tag.create!(tag_name: "舞台")
Tag.create!(tag_name: "マクべクス")
Tag.create!(tag_name: "笑いあり")
Tag.create!(tag_name: "涙あり")
Tag.create!(tag_name: "海外")
Tag.create!(tag_name: "美術館")
Tag.create!(tag_name: "近現代アート")
Tag.create!(tag_name: "一日目")
Tag.create!(tag_name: "二日目")
Tag.create!(tag_name: "お笑い")
Tag.create!(tag_name: "漫才")
Tag.create!(tag_name: "お笑いライブ")
Tag.create!(tag_name: "若手芸人")
Tag.create!(tag_name: "2022/3/3")

TagMap.create!(post_id: 6, tag_id: 1)
TagMap.create!(post_id: 6, tag_id: 2)
TagMap.create!(post_id: 6, tag_id: 3)
TagMap.create!(post_id: 5, tag_id: 4)
TagMap.create!(post_id: 5, tag_id: 5)
TagMap.create!(post_id: 5, tag_id: 6)
TagMap.create!(post_id: 4, tag_id: 7)
TagMap.create!(post_id: 4, tag_id: 8)
TagMap.create!(post_id: 3, tag_id: 9)
TagMap.create!(post_id: 3, tag_id: 10)
TagMap.create!(post_id: 3, tag_id: 11)
TagMap.create!(post_id: 2, tag_id: 12)
TagMap.create!(post_id: 2, tag_id: 13)
TagMap.create!(post_id: 2, tag_id: 14)
TagMap.create!(post_id: 1, tag_id: 1)
TagMap.create!(post_id: 1, tag_id: 15)
TagMap.create!(post_id: 1, tag_id: 16)
TagMap.create!(post_id: 1, tag_id: 17)
TagMap.create!(post_id: 9, tag_id: 4)
TagMap.create!(post_id: 9, tag_id: 18)
TagMap.create!(post_id: 9, tag_id: 20)
TagMap.create!(post_id: 8, tag_id: 21)
TagMap.create!(post_id: 8, tag_id: 22)
TagMap.create!(post_id: 8, tag_id: 23)
TagMap.create!(post_id: 8, tag_id: 24)
TagMap.create!(post_id: 7, tag_id: 12)
TagMap.create!(post_id: 7, tag_id: 25)
TagMap.create!(post_id: 7, tag_id: 26)
TagMap.create!(post_id: 12, tag_id: 11)
TagMap.create!(post_id: 12, tag_id: 10)
TagMap.create!(post_id: 12, tag_id: 27)
TagMap.create!(post_id: 12, tag_id: 28)
TagMap.create!(post_id: 11, tag_id: 30)
TagMap.create!(post_id: 11, tag_id: 31)
TagMap.create!(post_id: 10, tag_id: 32)
TagMap.create!(post_id: 10, tag_id: 33)
TagMap.create!(post_id: 15, tag_id: 34)
TagMap.create!(post_id: 15, tag_id: 35)
TagMap.create!(post_id: 14, tag_id: 36)
TagMap.create!(post_id: 14, tag_id: 37)
TagMap.create!(post_id: 14, tag_id: 38)
TagMap.create!(post_id: 13, tag_id: 39)
TagMap.create!(post_id: 13, tag_id: 40)
TagMap.create!(post_id: 13, tag_id: 41)
TagMap.create!(post_id: 13, tag_id: 42)
TagMap.create!(post_id: 18, tag_id: 43)
TagMap.create!(post_id: 18, tag_id: 44)
TagMap.create!(post_id: 18, tag_id: 45)
TagMap.create!(post_id: 17, tag_id: 43)
TagMap.create!(post_id: 17, tag_id: 44)
TagMap.create!(post_id: 16, tag_id: 43)
TagMap.create!(post_id: 16, tag_id: 44)
TagMap.create!(post_id: 16, tag_id: 46)
TagMap.create!(post_id: 17, tag_id: 47)
TagMap.create!(post_id: 21, tag_id: 48)
TagMap.create!(post_id: 21, tag_id: 49)
TagMap.create!(post_id: 20, tag_id: 50)
TagMap.create!(post_id: 20, tag_id: 32)
TagMap.create!(post_id: 20, tag_id: 51)
TagMap.create!(post_id: 20, tag_id: 52)

Favorite.create!(user_id: 1, post_id: 15)
Favorite.create!(user_id: 1, post_id: 20)
Favorite.create!(user_id: 1, post_id: 10)
Favorite.create!(user_id: 2, post_id: 6)
Favorite.create!(user_id: 2, post_id: 16)
Favorite.create!(user_id: 3, post_id: 14)
Favorite.create!(user_id: 3, post_id: 9)
Favorite.create!(user_id: 4, post_id: 20)
Favorite.create!(user_id: 10, post_id: 21)
Favorite.create!(user_id: 10, post_id: 20)
Favorite.create!(user_id: 10, post_id: 6)
Favorite.create!(user_id: 10, post_id: 1)
Favorite.create!(user_id: 6, post_id: 4)
Favorite.create!(user_id: 6, post_id: 1)

PostComment.create!(user_id: 1, post_id: 20, comment: "楽しそうですね！")
PostComment.create!(user_id: 1, post_id: 16, comment: "いつか行ってみたいです")
PostComment.create!(user_id: 1, post_id: 10, comment: "行きたいです！")
PostComment.create!(user_id: 2, post_id: 6, comment: "綺麗ですね")
PostComment.create!(user_id: 2, post_id: 16, comment: "私も昔行ったことがあります。")
PostComment.create!(user_id: 2, post_id: 12, comment: "素敵なbarですね")
PostComment.create!(user_id: 3, post_id: 10, comment: "ぜひお越しください！")
PostComment.create!(user_id: 3, post_id: 14, comment: "私も一度見に行ったことがあります。素敵なショーでした。")
PostComment.create!(user_id: 3, post_id: 3, comment: "私も行きました！")
PostComment.create!(user_id: 4, post_id: 20, comment: "面白そう")
PostComment.create!(user_id: 4, post_id: 9, comment: "素敵な演出ですね")
PostComment.create!(user_id: 10, post_id: 20, comment: "行きます！")
PostComment.create!(user_id: 10, post_id: 1, comment: "素敵な雰囲気です")
PostComment.create!(user_id: 6, post_id: 4, comment: "Degiがおすすめです")

Notification.create!(visitor_id: 1, visited_id: 4, post_id: 15, post_comment_id: nil, event_id: nil, ticket_id: nil, action: "like", checked: true)
Notification.create!(visitor_id: 1, visited_id: 9, post_id: 20, post_comment_id: 1, event_id: nil, ticket_id: nil, action: "comment", checked: false)
Notification.create!(visitor_id: 1, visited_id: 9, post_id: 20, post_comment_id: nil, event_id: nil, ticket_id: nil, action: "like", checked: false)
Notification.create!(visitor_id: 1, visited_id: 5, post_id: 16, post_comment_id: 2, event_id: nil, ticket_id: nil, action: "comment", checked: true)
Notification.create!(visitor_id: 1, visited_id: 3, post_id: 10, post_comment_id: 3, event_id: nil, ticket_id: nil, action: "comment", checked: true)
Notification.create!(visitor_id: 1, visited_id: 3, post_id: 10, post_comment_id: nil, event_id: nil, ticket_id: nil, action: "like", checked: true)
Notification.create!(visitor_id: 2, visited_id: 1, post_id: 6, post_comment_id: nil, event_id: nil, ticket_id: nil, action: "like", checked: false)
Notification.create!(visitor_id: 2, visited_id: 1, post_id: 6, post_comment_id: 4, event_id: nil, ticket_id: nil, action: "comment", checked: false)
Notification.create!(visitor_id: 2, visited_id: 5, post_id: 16, post_comment_id: nil, event_id: nil, ticket_id: nil, action: "like", checked: true)
Notification.create!(visitor_id: 2, visited_id: 1, post_id: 16, post_comment_id: 5, event_id: nil, ticket_id: nil, action: "comment", checked: false)
Notification.create!(visitor_id: 2, visited_id: 3, post_id: 12, post_comment_id: 6, event_id: nil, ticket_id: nil, action: "comment", checked: true)
Notification.create!(visitor_id: 3, visited_id: 1, post_id: 10, post_comment_id: 7, event_id: nil, ticket_id: nil, action: "comment", checked: false)
Notification.create!(visitor_id: 3, visited_id: 4, post_id: 14, post_comment_id: 8, event_id: nil, ticket_id: nil, action: "comment", checked: true)
Notification.create!(visitor_id: 3, visited_id: 4, post_id: 14, post_comment_id: nil, event_id: nil, ticket_id: nil, action: "like", checked: true)
Notification.create!(visitor_id: 3, visited_id: 1, post_id: 3, post_comment_id: 9, event_id: nil, ticket_id: nil, action: "comment", checked: false)
Notification.create!(visitor_id: 3, visited_id: 2, post_id: 9, post_comment_id: nil, event_id: nil, ticket_id: nil, action: "like", checked: false)
Notification.create!(visitor_id: 4, visited_id: 1, post_id: 20, post_comment_id: 10, event_id: nil, ticket_id: nil, action: "comment", checked: false)
Notification.create!(visitor_id: 4, visited_id: 9, post_id: 20, post_comment_id: nil, event_id: nil, ticket_id: nil, action: "like", checked: false)
Notification.create!(visitor_id: 4, visited_id: 2, post_id: 9, post_comment_id: 11, event_id: nil, ticket_id: nil, action: "comment", checked: false)
Notification.create!(visitor_id: 10, visited_id: 9, post_id: 21, post_comment_id: nil, event_id: nil, ticket_id: nil, action: "like", checked: false)
Notification.create!(visitor_id: 10, visited_id: 1, post_id: 20, post_comment_id: 12, event_id: nil, ticket_id: nil, action: "comment", checked: false)
Notification.create!(visitor_id: 10, visited_id: 4, post_id: 20, post_comment_id: 12, event_id: nil, ticket_id: nil, action: "comment", checked: false)
Notification.create!(visitor_id: 10, visited_id: 9, post_id: 20, post_comment_id: nil, event_id: nil, ticket_id: nil, action: "like", checked: false)
Notification.create!(visitor_id: 10, visited_id: 1, post_id: 6, post_comment_id: nil, event_id: nil, ticket_id: nil, action: "like", checked: false)
Notification.create!(visitor_id: 10, visited_id: 1, post_id: 1, post_comment_id: 13, event_id: nil, ticket_id: nil, action: "comment", checked: false)
Notification.create!(visitor_id: 10, visited_id: 1, post_id: 1, post_comment_id: nil, event_id: nil, ticket_id: nil, action: "like", checked: false)
Notification.create!(visitor_id: 6, visited_id: 1, post_id: 4, post_comment_id: nil, event_id: nil, ticket_id: nil, action: "like", checked: false)
Notification.create!(visitor_id: 6, visited_id: 1, post_id: 4, post_comment_id: 14, event_id: nil, ticket_id: nil, action: "comment", checked: false)
Notification.create!(visitor_id: 6, visited_id: 1, post_id: 1, post_comment_id: nil, event_id: nil, ticket_id: nil, action: "like", checked: false)

Room.create!
Room.create!
Room.create!

UserRoom.create!(user_id: 1, room_id: 1)
UserRoom.create!(user_id: 3, room_id: 1)
UserRoom.create!(user_id: 1, room_id: 2)
UserRoom.create!(user_id: 2, room_id: 2)
UserRoom.create!(user_id: 10, room_id: 3)
UserRoom.create!(user_id: 9, room_id: 3)

Chat.create!(user_id: 1, room_id: 1, message: "初めまして。突然のご連絡失礼致します。\n最近コンサートに行ってジャズが好きになりました。", checked: true)
Chat.create!(user_id: 1, room_id: 1, message: "ジャズコンサートをされるとのことで、是非行かせていただきたいです。", checked: true)
Chat.create!(user_id: 1, room_id: 2, message: "こんにちは！私もライブ大好きです。", checked: true)
Chat.create!(user_id: 1, room_id: 2, message: "好きなアーティストの方はいらっしゃいますか ？", checked: true)
Chat.create!(user_id: 2, room_id: 2, message: "こん にちは！\n私は「moon」が好きです", checked: false)
Chat.create!(user_id: 3, room_id: 1, message: "ご連絡ありがとうございます。是非お越しください！", checked: false)
Chat.create!(user_id: 3, room_id: 1, message: "詳細は追ってご連絡いたしますね", checked: false)
Chat.create!(user_id: 10, room_id: 3, message: "こんにちは。私もお笑い大好きです！好きなお笑い芸人 はいらっしゃいますか？", checked: false)